[package]
name = "wave-function-collapse"
version = "0.1.0"
edition = "2021"
description = "Implementation of wave function collapse targetting wasm"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.91"